# Generated by Django 5.1.4 on 2024-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MR', 'Mahindra'), ('TY', 'Toyota'), ('SU', 'Suzuki'), ('PO', 'Porscher'), ('RR', 'Rols Royal'), ('TT', 'Tata'), ('BMW', 'BMW'), ('VO', 'Volkswagen'), ('ME', 'Mercedes'), ('RA', 'Range Rower'), ('AD', 'Audi')], max_length=3),
        ),
    ]
