# Generated by Django 5.1.4 on 2024-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('MR', 'Mahindra'), ('TY', 'Toyota'), ('sz', 'Suzuki'), ('PY', 'poshture'), ('RY', 'Rols Royal'), ('TT', 'tata'), ('BMW', 'BMW'), ('wv', 'Volkswagen'), ('MD', 'Mercedes'), ('RG', 'range Rower'), ('OD', 'Audi')], max_length=3)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
