# Generated by Django 5.1.4 on 2024-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MR', 'Mahindra'), ('TY', 'Toyota'), ('SZ', 'Suzuki'), ('PY', 'Porscher'), ('RY', 'Rols Royal'), ('TT', 'Tata'), ('BMW', 'BMW'), ('WV', 'Volkswagen'), ('MD', 'Mercedes'), ('RG', 'Range Rower'), ('OD', 'Audi')], max_length=3),
        ),
    ]
